spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.7.80:3306/es_rep?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  application:
    name: es-rep
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9100

