spring:
  cloud:
    gateway:
      routes:
        - id: rep_route
          uri: lb://es-rep
          predicates:
            - Path=/api/rep/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: rep_search
          uri: lb://es-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: dep_route
          uri: lb://es-dep
          predicates:
            - Path=/api/dep/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848